{pos: 1,	num: 22,	driver: "Jenson Button",		contructor: "Brawn",		laps: 57,	grid: 4,	time: "1:31:48.182",	status: "Finished",	points: 10},
{pos: 2,	num: 15,	driver: "Sebastian Vettel",		contructor: "Red Bull",		laps: 57,	grid: 3,	time: "+7.187",			status: "Finished",	points: 8},
{pos: 3,	num: 9,		driver: "Jarno Trulli",			contructor: "Toyota",		laps: 57,	grid: 1,	time: "+9.170",			status: "Finished",	points: 6},
{pos: 4,	num: 1,		driver: "Lewis Hamilton",		contructor: "McLaren",		laps: 57,	grid: 5,	time: "+22.096",		status: "Finished",	points: 5},
{pos: 5,	num: 23,	driver: "Rubens Barrichello",	contructor: "Brawn",		laps: 57,	grid: 6,	time: "+37.779",		status: "Finished",	points: 4},
{pos: 6,	num: 4,		driver: "Kimi Räikkönen",		contructor: "Ferrari",		laps: 57,	grid: 10,	time: "+42.057",		status: "Finished",	points: 3},
{pos: 7,	num: 10,	driver: "Timo Glock",			contructor: "Toyota",		laps: 57,	grid: 2,	time: "+42.880",		status: "Finished",	points: 2},
{pos: 8,	num: 7,		driver: "Fernando Alonso",		contructor: "Renault",		laps: 57,	grid: 7,	time: "+52.775",		status: "Finished",	points: 1},
{pos: 9,	num: 16,	driver: "Nico Rosberg",			contructor: "Williams",		laps: 57,	grid: 9,	time: "+58.198",		status: "Finished",	points: 0},
{pos: 10,	num: 8,		driver: "Nelson Piquet Jr.",	contructor: "Renault",		laps: 57,	grid: 15,	time: "+1:05.149",		status: "Finished",	points: 0},
{pos: 11,	num: 14,	driver: "Mark Webber",			contructor: "Red Bull",		laps: 57,	grid: 18,	time: "+1:07.641",		status: "Finished",	points: 0},
{pos: 12,	num: 2,		driver: "Heikki Kovalainen",	contructor: "McLaren",		laps: 57,	grid: 11,	time: "+1:17.824",		status: "Finished",	points: 0},
{pos: 13,	num: 11,	driver: "Sébastien Bourdais",	contructor: "Toro Rosso",	laps: 57,	grid: 20,	time: "+1:18.805",		status: "Finished",	points: 0},
{pos: 14,	num: 3,		driver: "Felipe Massa",			contructor: "Ferrari",		laps: 56,	grid: 8,	time: "",				status: "+1 Lap",	points: 0},
{pos: 15,	num: 21,	driver: "Giancarlo Fisichella",	contructor: "Force India",	laps: 56,	grid: 17,	time: "",				status: "+1 Lap",	points: 0},
{pos: 16,	num: 20,	driver: "Adrian Sutil",			contructor: "Force India",	laps: 56,	grid: 19,	time: "",				status: "+1 Lap",	points: 0},
{pos: 17,	num: 12,	driver: "Sébastien Buemi",		contructor: "Toro Rosso",	laps: 56,	grid: 16,	time: "",				status: "+1 Lap",	points: 0},
{pos: 18,	num: 5,		driver: "Robert Kubica",		contructor: "BMW Sauber",	laps: 56,	grid: 13,	time: "",				status: "+1 Lap",	points: 0},
{pos: 19,	num: 6,		driver: "Nick Heidfeld",		contructor: "BMW Sauber",	laps: 56,	grid: 14,	time: "",				status: "+1 Lap",	points: 0},
{pos: R,	num: 17,	driver: "Kazuki Nakajima",		contructor: "Williams",		laps: 48,	grid: 12,	time: "",				status: "Oil pressure",	points: 0}